### ISSUE TITLE
Deny all permissions until explicitly granted

### ISSUE THREAD

**Issue by bohrsty** [fxpio/fxp-security-bundle#15]
Hi @francoispluchino,
I have another question on your bundle, because I cannot find my error. I tried to "deny all permissions" for my Navi entity, but as a result I get the list of all entities that my `findBy(...)` method would retrieve from database if I wouldn't use permission config, but without any field filled (i.e. id is null, strings and array collections are empty)...

I tried to deny permission for all with this configuration:
```yaml
# sonatra security configuration
sonatra_security:
    role_class: AppBundle\Entity\Role
    permission_class: AppBundle\Entity\Permission
    sharing_class: AppBundle\Entity\Sharing
    object_filter:
        enabled: true # Enable the object filter (optional)
    role_hierarchy:
        enabled: true # Enable the role hierarchy for organizational context (optional)
        cache: null # Defined the service cache for role hierarchy (optional)
    security_voter:
        role_security_identity: true # Override the Symfony Role Hierarchy Voter (optional)
        groupable: true # Enable to check the group in the Symfony Security Authorization Checker
    sharing:
        enabled: true
        identity_types:
            AppBundle\Entity\User:
                roleable: true # (optional)
            AppBundle\Entity\Role:
                permissible: true # (optional)
    default_permissions:
        master_mapping_permissions:
            view:      read
            update:    edit
            create:    edit
            delete:    edit
    permissions:
        AppBundle\Entity\Navi:
            enabled: true
    doctrine:
        orm:
            object_filter_voter: true # Ebable the Doctrine ORM Collection Object Filter (optional)
            listeners:
                permission_checker: true # Enable the Doctrine ORM Permission Checker Listener (optional)
                object_filter: true # Enable the Doctrine ORM Object Filter Listener(optional)
                role_hierarchy: true # Enable the Doctrine ORM listener of role hierarchy (optional)
            filters:
                sharing: true # Enable the Doctrine ORM SQL Filter for sharing the entities (optional)
```

(where in
```yaml
    permissions:
        AppBundle\Entity\Navi:
```
I also tried `operations: []` or `master: ~`, all with the same result)

and would have expected to get an empty result from this `findBy()` call:
```php
$repositoryNavi = $this->em->getRepository('AppBundle:Navi');
$naviEntries = $repositoryNavi->findBy(
	array(
		'parent' => null,
		'valid' => true,
		'show' => true
	),
	array('position' => 'ASC')
);
```

Have I misunderstood something, or what would the correct way to deny all permissions for any user/group/role (afterwards I want to use sharing to grant permissions to individual users/groups/roles)?

**Comment by francoispluchino** [comment]
linear-gradient(to bottom right, transparent, transparent 51%, #e2efc7 49%, #e2efc7 )
linear-gradient(to top left, transparent, transparent 51%, #e2efc7 49%, #e2efc7 )


- Ajouter page vide avec lien pr créer nouvelle propirété
- charger options.bookings a l'init

-----------------------------------------------------------

php bin/console doctrine:ensure-production-settings
php bin/console doctrine:database:extensions:load
php bin/console doctrine:migrations:migrate
php bin/console init:platform

Attacher la stategy AmazonEC2ContainerRegistryReadOnly sur le role utiliser par Beanstalk pour EC2

----

There is a difference between permission and sharing. The permissions tell you whether the user, role, or group have access rights based on operations (view, create, etc...), and if the Object Filter is enabled, the entity is cleaned at loading, leaving only the Id (always) and the authorized field values. However, permissions do not filter the doctrine queries. To do this, you must enable (you have already done so) and configure the sharing:

For entities to be filtered at the time of the Doctrine query, you have the option to build your own `SQLFilter`, Or use the `SharingFilter` class in this bundle (see the [doc](https://github.com/sonatra/sonatra-security-bundle/blob/master/Resources/doc/index.md#step-8-configure-your-applications-configyml)):

```yaml
doctrine:
    orm:
        entity_managers:
            default:
                filters:
                    sonatra_sharing:
                        class:      Sonatra\Component\Security\Doctrine\ORM\Filter\SharingFilter
                        enabled:    true
```

This filter requires a small configuration to know what you want to do with it. By default, the sharing for all classes is disabled (`none` value), but in your case, you will use the `private` value for all class that need a sharing, and for that, you will need to add this configuration:

```yaml
sonatra_security:
    sharing:
        subjects:
            AppBundle\Entity\Navi: private
```

You will find the values and their descriptions in the class `Sonatra\Component\Security\SharingVisibilities`.

In this way you enable the `SQLFilter` to filter any entity that is not shared with either a user, a role, a group, or an organization.

**Comment by bohrsty** [comment]
I adjusted my configuration and added the sharing configuration for the Navi entity, now I'm getting an error 500 with the following log entry I cannot really interpret:

> [2017-07-10 20:35:58] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Syntax Error] line 0, col 149: Error: Expected known function, got 'AND'" at /path/to/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 52 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Syntax Error] line 0, col 149: Error: Expected known function, got 'AND' at /path/to/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:52, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT s, p FROM AppBundle\\Entity\\Sharing s LEFT JOIN s.permissions p WHERE ((s.subjectClass = :subject0_class AND s.subjectId = :subject0_id)) AND  AND (s.enabled = TRUE AND (s.startedAt IS NULL OR s.startedAt <= CURRENT_TIMESTAMP()) AND (s.endedAt IS NULL OR s.endedAt >= CURRENT_TIMESTAMP())) ORDER BY p.class asc, p.field asc, p.operation asc at /path/to/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []

I know, that `AND  AND` isn't valid SQL, but I cannot see where it comes from...

**Comment by francoispluchino** [comment]
Can you give me more configuration?

**Comment by bohrsty** [comment]
I pushed my current configuration along with the rest of the local development files to a temporary public branch https://github.com/bohrsty/judointranet/tree/error-sonatra-security/app/config/

the running `parameters.yml` file is the following:
 ```yml
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: user
    database_user: database
    database_password: password
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: root@localhost
    mailer_password: null
    secret: secret
```

**Comment by bohrsty** [comment]
Hi @francoispluchino,
any news about this? Or do you need some more informations?

Thanks and kind regards
bohrsty

**Comment by francoispluchino** [comment]
Can you create a repository containing the symfony standard edition, this bundle and a config to reproduce this bug, because I can not reproduce your error. I could watch today.

**Comment by bohrsty** [comment]
Sorry for the delay, there were something to do with higher priority...

Maybe I could create such repository, but my project is nearly what you ask for... all that legacy code does not really interfere with anything in symfony, it just uses the routing, the controller generates a legacy object, the object does its magic and return HTML, that is delivered as a symfony response by the controller...

But I could find a bit more about the error:
it comes from `Sonatra\Component\Security\Doctrine\ORM\Provider\SharingProvider::addWhereSecurityIdentitiesForSharing()`, if in [line 234](https://github.com/sonatra/sonatra-security/blob/687de4a5afadcd03dd1aa88b1addefb9b3c3915f/Doctrine/ORM/Provider/SharingProvider.php#L234) `$groupSids` is an empty array, it adds an empty string in `andWhere()` that is obviously leading to the SQL error...

In my case the `var_dump()` of `$sids` in [line 234](https://github.com/sonatra/sonatra-security/blob/687de4a5afadcd03dd1aa88b1addefb9b3c3915f/Doctrine/ORM/Provider/SharingProvider.php#L234) is the following:
```
[0]
   object(Sonatra\Component\Security\Identity\RoleSecurityIdentity)[659]
      protected 'type' => string 'role' (length=4)
      protected 'identifier' => string 'IS_AUTHENTICATED_ANONYMOUSLY' (length=28)
```
Could maybe the anonymous token be an edge case here? If I add an if clause for testing
```php
if($where !== '') {
        $qb->andWhere($where);
}
```
it works without SQL error... but the result is the same as in my initital question:

> but as a result I get the list of all entities that my `findBy(...)` method would retrieve from database if I wouldn't use permission config, but without any field filled (i.e. id is null, strings and array collections are empty)

You maybe have an idea why?

**Comment by francoispluchino** [comment]
Regarding the empty array in the where condition, can you create an issue, as this is a bug. Because all Role Security Identity starting with `IS_` are skipped.

For your last question, in your case, the `ObjectFilter` service is activated, like I said above, the objects are "cleaned up" of their values if the user does not have the permissions to read each field. But if the sharing SQL filter is not enabled, you still get the list, but with empty objects. To avoid that, you can disable the `ObjectFilter` if it is not necessary for you, or enable the Sharing SQL Filter (to clean the list of Doctrine result).

Regarding the `SharingProvider`, if you enable sharing, a doctrine filter will filter your queries to get only the records that the logged user has the right to see. It adds where conditions in SQL based on all user security identities (`RoleSecurityIdentity`, `GroupSecurityIdentity`, `UserSecurityIdentity`, `OrganizationSecurityIdentity`).

So if you have defined your share on `private`, and there is no defined share, your Doctrine query will be an empty list. So that it is not empty, you must define a share for the record defined on a role, a group or directly on a user.

See the debug toolbar of Doctrine to get the where conditions defined in the SQL.

**Comment by bohrsty** [comment]
I opened the issue about the `IS_` Role Security Identity ([sonatra-security issue 2](https://github.com/sonatra/sonatra-security/issues/2))...

> So if you have defined your share on `private`, and there is no defined share, your Doctrine query will be an empty list. So that it is not empty, you must define a share for the record defined on a role, a group or directly on a user.

I did defined the share on my Navi entity as `private`, I didn't defined any share and the ObjectFilter is enabled (as you stated), but the result is not empty, only all fields are cleared out, because there is no permission for the anonymous role identity.
Is there maybe another issue with the anonymous role identity?

Just to be sure, that there is no error in my configuration, here is the complete configuration running and not returning an empty shared list:

```yaml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  null
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        schema_filter: ~^(orm_.*|migration_versions|fos_.*|son_.*)~

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                filters:
                    sonatra_sharing:
                        class:      Sonatra\Component\Security\Doctrine\ORM\Filter\SharingFilter
                        enabled:    true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/Migrations"
    namespace: JudoIntranetMigrations
    table_name: migration_versions
    name: JudoIntranet Migrations

# user configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    group:
        group_class: AppBundle\Entity\Group

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# sonatra security configuration
sonatra_security:
    role_class: AppBundle\Entity\Role
    permission_class: AppBundle\Entity\Permission
    sharing_class: AppBundle\Entity\Sharing
    object_filter:
        enabled: true # Enable the object filter (optional)
    role_hierarchy:
        enabled: true # Enable the role hierarchy for organizational context (optional)
        cache: null # Defined the service cache for role hierarchy (optional)
    security_voter:
        role_security_identity: true # Override the Symfony Role Hierarchy Voter (optional)
        groupable: true # Enable to check the group in the Symfony Security Authorization Checker
    sharing:
        enabled: true
        identity_types:
            AppBundle\Entity\User:
                roleable: true # (optional)
            AppBundle\Entity\Role:
                permissible: true # (optional)
        subjects:
            AppBundle\Entity\Navi: private
    default_permissions:
        master_mapping_permissions:
            view:      read
            update:    edit
            create:    edit
            delete:    edit
    permissions:
        AppBundle\Entity\Navi:
            enabled: true
    doctrine:
        orm:
            object_filter_voter: true # Ebable the Doctrine ORM Collection Object Filter (optional)
            listeners:
                permission_checker: true # Enable the Doctrine ORM Permission Checker Listener (optional)
                object_filter: true # Enable the Doctrine ORM Object Filter Listener(optional)
                role_hierarchy: true # Enable the Doctrine ORM listener of role hierarchy (optional)
            filters:
                sharing: true # Enable the Doctrine ORM SQL Filter for sharing the entities (optional)
```

**Comment by francoispluchino** [comment]
If I understood correctly, you want the result of a Doctrine query to return no records, whereas this is not the case. However, there is no user logged in, but is a anonymous user. All Role Security Identities starting with `IS_` are not used by the sharing filter because they are not real roles, but a state of the authentication. So, no real role is present for the anonymous user.

So, to add automatically a role for the anonymous token, you must enable the `anonymous_role` feature and configure your security firewall:

```yaml
sonatra_security:
    anonymous_role:
        enabled: true

security:
    firewalls:
        main:
            anonymous:      true # already added
            anonymous_role: true
```

The `anonymous_role` key can be a boolean or a string. If the value is a boolean, it's as if you define the role `ROLE_ANONYMOUS`. Of course, you can define any role, like `ROLE_FOO_BAR` (in the same genre there is a feature to do the same thing but based on the name of the host, if you must define different permissions for each website).

Of course you can create the `ROLE_ANONYMOUS` role and defined the permissions and sharing.

If you would define the permissions for the anonymous user, you must create a specific role ROLE_ANONYMOUS, and define this role in your security firewall. After, you can add the permissions for the anoymous role.

I know, it's true that this is not the behavior we can expect at first, but it's normal, because your security identity manager has no user, group or role identities, and as a result, the sharing SQL filter is not used, and so, your doctrine query is not filtered.

By enabling the anonymous role in your configuration, your security identity manager will not be empty (a RoleSecurityIdentity with `ROLE_ANONYMOUS` should be present, or with your custom role name), and the sharing sql filter will be used.

**Comment by bohrsty** [comment]
Ok, thank you that far... You understood correctly, I actually haven't defined any permission or sharing, so I expect that any doctrine query does return an empty result...  but just adding the configuration for `anonymous_role` you suggested didn't change anything...

Maybe I missed that one: do I have to create a `ANONYMOUS_ROLE` or should enabling the `anonymous_role` do the trick?

**Comment by francoispluchino** [comment]
Normally, it's not necessary to create the role ROLE_ANONYMOUS. Can you create a repository containing the symfony standard edition, this bundle and a config to reproduce your problem?

**Comment by bohrsty** [comment]
I think so, but I need a few days to adjust the classes and entities...

**Comment by bohrsty** [comment]
got it (not ;-) ) running today...
please clone [bohrsty/test-sonatra-secutity-bundle](https://github.com/bohrsty/test-sonatra-secutity-bundle), run `composer install` and `bin/console doctrine:migration:migrate` to insert some test-data and browse to `/api/v2/navi/` (webserver-bundle isn't installed, so the `server:*` commands are not available)...
This repository only contains the bundles you requested and their dependencies, my original entities, my original configuration and a controller to catch the route... my result is an array of 7 entities (`var_dump()`) and any of the fields is null or empty arrays...

**Comment by bohrsty** [comment]
Hi @francoispluchino,
could you find anything but my typo in the repository name?

**Comment by francoispluchino** [comment]
I have not had time to look yet. I think I'll have a little bit tomorrow.

**Comment by francoispluchino** [comment]
Hi @bohrsty,

I fixed the syntax error when the list of security identities is empty for the `private` Doctrine SQL filter (see sonatra/sonatra-security@a46c3c7121c896e313a753455ec8670a0cab1e2b). I also updated the doc for sharing configuration (d11ae13782c4e7c06347558b68f7110a35b1ccd1). Your example now returns an empty list after you configure the `private` SQL filter:

```yaml
# app/config/config.yml
sonatra_security:
    doctrine:
        orm:
            listeners:
                private_sharing: true # Enable the 'private' sharing filter type
                sharing_delete:  true # Enable the auto sharing delete when the entity is deleted
```

Regarding your configuration, I recommend you several points:

#### Anonymous Role

If you want to add permissions on entities for all anonymous users, you must enable the `anonymous_role` feature and configure your security firewall:

```yaml
# app/config/security.yml
security:
    firewalls:
        main:
            anonymous_role: true
```

#### Object Filter

If you do not have the need to clean the object values based on permissions, you can disable the `object_filter` service:

```yaml
# app/config/config.yml
sonatra_security:
    object_filter:
        enabled: false
```

Or, if you want to use the `object_filter` service, I recommend that you use the transactional mode of the service each time you do a Doctrine request, allowing you to optimize the retriving of permissions for all objects and all fields in one request, for the list obtained. Otherwise, a query will be made for each object and each field of the object after Doctrine loads each object.

To resume your controller in your example:

```php
namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class NaviController extends Controller
{    
    public function indexAction(Request $request)
    {
        // begin the transaction
        $this->get('sonatra_security.object_filter')->beginTransaction();

        $repositoryNavi = $this->getDoctrine()->getRepository('AppBundle:Navi');
        $naviEntries = $repositoryNavi->findBy(
            array(
                'parent' => null,
                'valid' => true,
                'show' => true
            ),
            array('position' => 'ASC')
        );

        $naviTree = array();
        foreach($naviEntries as $entry) {
            // exclude "homepage"
            if($entry->getId() != 1) {
                $naviTree[] = $entry->getNaviTree(2, 1);
            }
        }

        //clean field values of all entities in the transaction
        $this->get('sonatra_security.object_filter')->commit();
        
        return $this->render('default/index.html.twig');
    }
}
```
#### Conclusion

Now, you can add your permissions and your sharing entries for your:

- users
- roles (like `ROLE_ANONYMOUS` role, if you have enabled `anonymous_role`)
- groups

To add permissions or add sharing entries, you can use your favorite methods like Doctrine persist and Symfony Forms.
